# Site settings
title:
  es: Conversa Creativa
  en: Conversa Creativa
description:
  es: Abordamos retos de investigación aplicada en el ámbito de financiamiento climático.
  en: We address challenges of applied research in the field of climate finance.
index:
  es:
  en: home.html
email: emmanuel@conversamexico.com
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://www.conversamexico.com/" # the base hostname & protocol for your site

t:
  es:
    home:
      name: "INICIO"
      url: "/"
    especialidades:
      name: "ESPECIALIDADES"
      url: "/especialidades.html"
    proyectos:
      name: "PROYECTOS"
      url: "/proyectos.html"
    equipo:
      name: "EQUIPO"
      url: "/equipo.html"

  en:
    home:
      name: "HOME"
      url: "/home.html"
    especialidades:
      name: "SPECIALITIES"
      url: "/specialities.html"
    proyectos:
      name: "PROJECTS"
      url: "/projects.html"
    equipo:
      name: "TEAM"
      url: "/team.html"

# Build settings
markdown: kramdown

sass:
    sass_dir: _sass
